### ISSUE TITLE
About whole body ...

### ISSUE THREAD

**Issue by JokerWooByAson** [Kariaro/VRigUnity#1]
Will the project support whole-body detection or even motion posture detection?

**Comment by Kariaro** [comment]
I just made this app to play around with different AI libraries and to try learn more about translating from AI generated data to 3D model poses.

I don’t think I’m going to add full body tracking but if I ever decide to make this app able to emulate vr controllers in games like vrchat I *might* do it.

I will maybe update how I calculate finger movement and facial expressions at some point though right now I don’t know if I will continue working on this project.
