### ISSUE TITLE
Add partial OSX/iOS support

### ISSUE THREAD

**Issue by Kariaro** [Kariaro/VRigUnity#10]
Compile this project for OSX/iOS and make sure the basic features work.
Virtual webcams are not required to work for this issue.

**Comment by Zumbalamambo** [comment]
Feature request: fullbody support :)

**Comment by Kariaro** [comment]
`feature/update-mediapipe` has been tested on OSX.
`StandaloneFileBrowser` and `Show Camera` does not work

A new option needs to be added to scale the UI. On newer macbook screens the buttons become way too small for normal usage

**Comment by Kariaro** [comment]
Build the ios libraries with Actions. The files are too large to upload to GitHub

**Comment by Kariaro** [comment]
This will be resolved in #15
