### ISSUE TITLE
about bug

### ISSUE THREAD

**Issue by JokerWooByAson** [Kariaro/VRigUnity#2]
I found several bugs. 
1. The accuracy of finger recognition is not enough. 
3. There is a problem with fist reversal. 
4. 3. The thumb is not recognized. 
5. 4. The left and right swing of fingers is not recognized. 
6. 5. It would be great if expression recognition could be added.

**Comment by Kariaro** [comment]
I wouldn’t call them bugs but improvements that could be made. I wrote about this in #1 

This was a training application I made and I might fix these in the future but I’m working on other projects right now 👍
