### ISSUE TITLE
Mapping the Legs

### ISSUE THREAD

**Issue by Zumbalamambo** [Kariaro/VRigUnity#3]
Thanks for the amazing example on mapping skeleton data to vrm. I'm using the following code to map the legs.
```

{
        Vector3 rKnee = ConvertPoint(eventArgs.value, 25);
        Vector3 rAnkle = ConvertPoint(eventArgs.value, 27);
        
        Vector3 vRigA = Vector3.right;
        Vector3 vRigB = rKnee - rhip;
        Quaternion rot = Quaternion.FromToRotation(vRigA, vRigB);
        rUpperLeg = rot;
        
        Vector3 vRigC = rAnkle - rKnee;
        rot = Quaternion.FromToRotation(vRigA, vRigC);
        rLowerLeg = rot;
}
```
But the mapping appears to be wrong. The leg is rotated and translated wrong. Anything wrong with the way that I compute the rotation?

**Comment by Kariaro** [comment]
Hi @Zumbalamambo

Thanks for the complements! :D

When I started writing the code I flipped left and right because I couldn't get the `VRM` model to render correctly when flipped.

I've not used any references when making my code so I can sadly not give you any sources but I can describe how I would solve this :+1:

```c#
// Fetch data points from Mediapipe
Vector3 rHip   = ConvertPoint(eventArgs.value, 23);
Vector3 rKnee  = ConvertPoint(eventArgs.value, 25);
Vector3 rAnkle = ConvertPoint(eventArgs.value, 27);
```

We know that the default vector of the **upperleg** to the **knee** is pointing downwards, we want to calculate the deviation from that vector

```c#
// If we were standing normally this would (*when normalized*) be close to (0, -1, 0)
Vector3 rHipKneeDiff    = rKnee - rHip;
Vector3 rHipKneeDefault = Vector3.down;

// Calculate the rotation needed to go from (0, -1, 0) to hip-knee vector
Quaternion rHipRotation = Quaternion.FromToRotation(rHipKneeDefault, rHipKneeDiff);

// Normally the knee-ankle vector is pointing in the same direction as the hip-knee vector
Vector3 rKneeAnkleDiff    = rAnkle - rKnee;
Vector3 rKneeAnkleDefault = rHipKneeDiff;

// Calculating the knee rotation can be done similarly.
Quaterion rKneeAnkle = Quaterion.FromToRotation(rKneeAnkleDefault, rKneeAnkleDiff);
```

I've not tested this code but I would write something similar to this

**Comment by Zumbalamambo** [comment]
@Kariaro thank you! I have adopted the code as follows,

```
rUpperLeg = rHipRotation;
rLowerLeg = rKneeAnkle;

```
Later setting the instance variables as follows,

```
this.rUpperLeg.Set(rUpperLeg,TimeNow);
this.rLowerLeg.Set(rLowerLeg,TimeNow);
```

and applied it to the vrm ,

```
rLowerLeg.UpdateRotation(animator.GetBoneTransform(HumanBodyBones.RightLowerLeg), time);
rUpperLeg.UpdateRotation(animator.GetBoneTransform(HumanBodyBones.RightUpperLeg), time);
```

Unfortunately, the leg is twisted backwards. Am I missing something? thanks again!

**Comment by Kariaro** [comment]
Hi @Zumbalamambo

I think this might be because vectors do not keep the forward direction.
The forward vector could be computed from the knee direction relative to the hip. I won’t be able to help with code for the next few days because I will not be at my computer.

**Comment by Zumbalamambo** [comment]
@Kariaro any references or directions might help. please share some.

**Comment by Zumbalamambo** [comment]
@Kariaro thanks for the hint!
