### ISSUE TITLE
"Start Camera" closes eyes on model.

### ISSUE THREAD

**Issue by DJSingleton** [Kariaro/VRigUnity#38]
I cannot get this to work at all, I downloaded DSSBodyTracker which was a clone of an older version of this project and that clone version actually worked, other than not sending anything through VMC. So I found the original (this project) and whenever I choose start camera the model's eyes close. It doesn't matter which camera I use. This results in this program being completely useless in it's current state.

**Comment by Kariaro** [comment]
I have no way to debug this.

What operative system are you using?
What version are you using?
Do you have a log file you could upload?
What camera are you using?

The newest version should allow you to turn off the face tracking (v0.2.0)

**Comment by Kariaro** [comment]
I believe this was caused by the faulty version v0.1.5 and you should update to v0.2.0
