### ISSUE TITLE
hips movement

### ISSUE THREAD

**Issue by saibai** [Kariaro/VRigUnity#71]
Hi, how can I free up the movement of the hips in 3D space? What is the part that is blocking the hips?
thanks

**Comment by Kariaro** [comment]
Currently the app can only add 3D rotations to the legs but it can’t move around in 3D. The hips are in a fixed position.

If this is something you want you could make a feature request 👍

**Comment by saibai** [comment]
I  developed an app for iPhone, and now I would like to be able to move the "VRM" avatar in 3D space. I would like to know which part of the code I should focus on in order to do this. Could you give me any advice or suggestions?and for sure the request feature;-)

**Comment by Kariaro** [comment]
You are allowed to reference parts of this code but you are not allowed to copy.

This project is source available meaning that I hold full copyright of the code but I also share code publicly.
This might change in the future but right now the code is locked.

---

If you want more resources on how to use Holistic Tracking you can read more on Mediapipes page:
https://google.github.io/mediapipe/solutions/holistic

You can also search for other examples or code that has been written in other repositories that does this.

You need to look at the data given from `Pose Landmarks` and estimate the 3D position. There are sources that can help you with how you convert from 2D screen space to 3D space.
I don't know how accurate the depth estimation is from the AI so you might have to tinker to get the values to look correct.

**Comment by saibai** [comment]
Thank you for the suggestions. I am developing an app for myself and I have only taken inspiration from your great project. If I ever decide to sell it, I will contact you to know what rights I have. My interest is to create an app for motion capture, to animate characters in Blender. So far, I have achieved good results, but it's certainly not complete.
