### ISSUE TITLE
How to make the VRM model walk?

### ISSUE THREAD

**Issue by wo-ai-tt** [Kariaro/VRigUnity#75]
Hello author! Your holistic motion capture is much smoother than what I wrote, thank you for making it open source. But I noticed a problem, I can't move the position of the VRM model in the scene. I have a VR treadmill. In my code, as long as I import the SDK of the VR treadmill, I can move the VRM model while motion capture. But in your code, I can't change the position of VRM. Can you tell me what to change in the code to move the VRM model?

**Comment by Kariaro** [comment]
This project is **source available** but not fully open source yet.

If this project becomes a bit more popular I will probably make it fully open source.

I made a class called HolisticMiodel that has Override Transforms on all bones in the model. If you want your treadmill to work you might be able to change the hip bone position through that class.

I’m using the animation rigging package for bone movement. You might get some more help searching for how other people hade done this with animation rigging.
