### ISSUE TITLE
Add full Linux support

### ISSUE THREAD

**Issue by Kariaro** [Kariaro/VRigUnity#9]
Find a way to implement `v4l2loopback` to allow virtual camera devices to be used on Linux.
Try find solutions that require as little maintenance as possible.

**Comment by orowith2os** [comment]
Something else that would help is allowing for packaging it on Linux, which would require a license to be added so that it can be sure that it's allowed. I'm down to help package it as a flatpak, I already maintain https://github.com/virtual-puppet-project/vpuppr on Flathub and Inochi Creator.

**Comment by Kariaro** [comment]
This issue is high maintenence and too vague
Future issues can be opened for specific features instead
