### ISSUE TITLE
 It can't work on Mac OS 13.2.1

### ISSUE THREAD

**Issue by oucqdcfzh** [Kariaro/VRigUnity#94]
### OS

Mac

### App Version

lastest version

### Description

After installing the app on my laptop, a MacBook Pro with the cpu M2, and the Mac OS 13.2.1, it didn't work. It shows the only hint "The application 'VRigUnity' cannot be opened."

**Comment by Kariaro** [comment]
Follow this tutorial and tell me if it works :3 https://m.youtube.com/watch?v=w8r2oMwsgMg

**Comment by oucqdcfzh** [comment]
It works! Thank you!
