### ISSUE TITLE
The arm won't move.

### ISSUE THREAD

**Issue by qq357075581** [Kariaro/VRigUnity#95]
Hi author, I copied the code into a new project (only the model and Solution nodes remain in the scenario). When running the project, the arms of the model will not move, and the upper body, head, and hands can move normally. Do you know what causes this? I turn on all the bone nodes when I can turn on the camera.This question has been bothering me for a long time...

![20240326150247](https://github.com/Kariaro/VRigUnity/assets/26922978/ff171ae3-0dc7-4127-af2b-708f67fe33e6)
`public void onBtnClick()
    {
        SetCamera(!isCameraShowing);
    }

    private void SetCamera(bool enable)
    {
        isCameraShowing = enable;
        for (int i = 0; i < 14; i++)
        {
            BoneSettings.Set(i, enable);
            SolutionUtils.GetSolution().Model.OnBoneUpdate(i, enable);
        }
        if (enable)
        {
            SolutionUtils.GetSolution().Play((_, _) => {
                // Error handling
                SetCamera(false);
            });
        }
        else
        {
            SolutionUtils.GetSolution().Model.ResetVRMAnimator();
            SolutionUtils.GetSolution().Stop();
        }
    }`
![20240326150148](https://github.com/Kariaro/VRigUnity/assets/26922978/6bb4d53f-93a4-4e9f-af8a-93dc890fb1c7)

**Comment by Kariaro** [comment]
It’s very hard to debug code when I don’t know how you’re using the code. If the head and hands works it sounds like the bone setting has arms turned off

**Comment by qq357075581** [comment]
Thank you very much. I think I found the reason. I made a mistake...

**Comment by qq357075581** [comment]
Read your project let me learn a lot, the author is too powerful!
